### ISSUE TITLE
Add no string content for HttpError

### ISSUE THREAD

**Issue by Lispython** [klen/adrest#14]
If raise HttpError with no string content (dict as example) it bring into unicode.
https://github.com/klen/adrest/blob/master/adrest/views.py#L170

If use python structures for HttpError/HttpResponse content we can create more usable response which can be serialized by given emitter.

**Comment by klen** [comment]
Done in version 1.1.0

```
raise HttpError(dict(test=True))
# or with custom emitter
raise HttpError(content, emitter=TextEmitter)
# HttpResponse always returned as is
# for emitted response has been added SerializedHttpResponse
return SerializedHttpResponse(content)
```
