### ISSUE TITLE
How does adrest compares to tastypie?

### ISSUE THREAD

**Issue by kra3** [klen/adrest#25]
Hi @klen, 

I'm looking for a rest solution for my-self.

Even though django-rest-framework is very good, it seems too much for my case. 

I liked your adrest & tastypie projects. I haven't looked into code base but just went through the main pages of both.

For me, both (adrest & tastypie) seems very very similar. Only notable difference I found is that your's using api versions &  other is using api naming. And yes, your example looks more neat. 

But, is there any good features in adrest that's not in tastypie?

@kra3

**Comment by klen** [comment]
I think tastypie is much better. Adrest — is internal tool as used in some custom projects.
