### ISSUE TITLE
Логика работы rpc_call

### ISSUE THREAD

**Issue by Lispython** [klen/adrest#26]
Привет.

https://github.com/klen/adrest/blob/master/adrest/resources/rpc.py#L101

Вот в этом куске кода в rpc_call аргумент `**kwargs`  он переопределяется умышленно или баг? В метод rpc хочется передавать дополнительные параметры типа объекта авторизации, но чтобы это сделать, надо в унаследованном rpc ресурсе переопределять всю логику метода rpc_call, без возможности вызвать родительский rpc_call, что не есть гуд.

**Comment by klen** [comment]
Ну по умолчанию RPC методы поддерживают только те параметры которые были указаны при вызове от клиента. С чем вызываем то и получаем.

В последних версиях adrest в **adrest.resources.rpc** есть декоратор **get_request**. Если обернуть в него реализацию RPC метода, то первым параметром в **всегда** будет приходить объект **request**, зачастую этого достаточно.

```
# где-то в реализации rpc
from adrest.resources.rpc import get_request

@get_request
def hello(request, text="Hello")
    return text + " " + request.user.username + "!"
```

При этом сигнатура вызова метода останется прежней {method: "hello", params: ["Welcome"]}
